# Generated by Django 4.2.4 on 2023-10-04 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myconfigurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myconfigurations.configurationcategory'),
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myconfigurations.configurationoption'),
        ),
    ]
