# Generated by Django 4.2.4 on 2023-10-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myconfigurations', '0002_alter_userconfiguration_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfiguration',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='configurationoption',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myconfigurations.configurationcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconfiguration',
            name='selected_options',
            field=models.ManyToManyField(related_name='user_configurations', to='myconfigurations.configurationoption'),
        ),
    ]
