# Generated by Django 4.2.4 on 2023-09-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_lesson_mediacontent_documentmedia_imagemedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmedia',
            options={'verbose_name': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='imagemedia',
            options={'verbose_name': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'verbose_name': 'Media Content'},
        ),
        migrations.AlterModelOptions(
            name='videomedia',
            options={'verbose_name': 'Videos'},
        ),
    ]
