# Generated by Django 4.2.6 on 2023-10-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
        migrations.AlterField(
            model_name='videomedia',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
