version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/blog/my-django-blog/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
  BeforeInstall:
    - location: scripts/install_dependencies
    - location: scripts/copy_env_file
  AfterInstall:
    - location: scripts/run_migrations
    - location: scripts/collect_static
  ApplicationStart:
    - location: scripts/start_server

  
  
