# Generated by Django 4.2.4 on 2023-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userquizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='user_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
