# Generated by Django 4.2.2 on 2023-06-16 22:49

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_comment_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
