# Generated by Django 4.2.2 on 2023-06-25 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
