# Generated by Django 4.2.4 on 2023-10-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_category_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
