name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop gunicorn
            
            sudo find /home/ubuntu/blog/my-django-blog/blog -path "*/__pycache__/*" -delete
            
            sudo cp /home/ubuntu/blog/.env /home/ubuntu/blog/my-django-blog/.env
            
            cd /home/ubuntu/blog/my-django-blog/
            source venv/bin/activate
            pip install -r requirements.txt
            
            python manage.py migrate
            
            python manage.py collectstatic --noinput
            
            sudo systemctl start gunicorn
            supervisorctl restart django_q
