name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop gunicorn
            
            # Remove existing project files except for the virtual environment and .env file
            find /home/ubuntu/blog/my-django-blog/ -mindepth 1 ! -name 'venv' ! -name '.env' -exec sudo rm -rf {} +
            
            # Sync new code to the server
            rsync -av --exclude='venv' --exclude='.env' ./ /home/ubuntu/blog/my-django-blog/
            
            # Restore the .env file
            sudo cp /home/ubuntu/blog/.env /home/ubuntu/blog/my-django-blog/.env
            
            cd /home/ubuntu/blog/my-django-blog/
            source venv/bin/activate
            
            # Ensure pip-tools is installed
            pip install pip-tools
            
            # Synchronize the environment with the requirements file
            pip-sync
            
            python manage.py migrate
            
            python manage.py collectstatic --noinput
            
            sudo systemctl start gunicorn
            supervisorctl restart django_q
